### ISSUE TITLE
Package name doesn't reflect usage

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Legacy.Sdk#10]
The package name is somehow very confusing and doesn't reflect the real usage. I first thought that the current SDK gets extracted into this SDK to allow SDK style csprojs with current Xamarin.Android.

But the purpose it to create multitargeting apps with "old" SDK and .NET6, so add this to SDK name, like `Xamarin.MultitargetingWithLegacyXamarin.Sdk`. This current name is confusing as hell.

**Comment by jonathanpeppers** [comment]
This package is still early stages, `0.1.0-alpha2`.

What text could we put here that would explain it better:

![image](https://user-images.githubusercontent.com/840039/106907891-59bb4380-66c4-11eb-8bca-45d887d74b5f.png)

Thanks.

**Comment by jonathanpeppers** [comment]
Let us know if you have other ideas, thanks. There is a full explanation here:

https://github.com/xamarin/Xamarin.Legacy.Sdk#what-is-this-when-would-i-need-it
