### ISSUE TITLE
Unable to find SDK  'Microsoft.Android.Sdk' error on mac using Visual Studio 2022 17.3.5

### ISSUE THREAD

**Issue by cyjimmy** [xamarin/Xamarin.Legacy.Sdk#43]
I am using the latest version of vs mac 17.3.5. When I tried to run the java binding sample project I got the error below:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/51365909/192058389-5fe527dd-8296-4956-8e01-9a7acd37a1af.png">
I saw this error mentioned in readme, but I have installed the latest Sdk and can run the MAUI sample fine.

**Comment by jonathanpeppers** [comment]
Are you using: https://www.nuget.org/packages/Xamarin.Legacy.Sdk/0.2.0-alpha2

We had to rename some .NET 6 packs for .NET 7, see: https://github.com/xamarin/Xamarin.Legacy.Sdk/commit/39e597ecf439b86c104bf3d8e5d17f6527f2a200

**Comment by cyjimmy** [comment]
Thanks for getting back to me. So what should I do to be able to run the java binding sample?
```
<Project Sdk="Xamarin.Legacy.Sdk/0.2.0-alpha2">
  <PropertyGroup>
    <TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
    <IsBindingProject>true</IsBindingProject>
    <!-- Hide some warnings -->
    <NoWarn>CS0108;CS0114;BG8700</NoWarn>
  </PropertyGroup>
</Project>
```
Do I add `<UseMicrosoftAndroidSdkNet6>true</UseMicrosoftAndroidSdkNet6>`?

**Comment by jonathanpeppers** [comment]
For that sample, you can either downgrade to `0.2.0-alpha1` or set `UseMicrosoftAndroidSdk`.

Basically what happened is we renamed the packs -- but it works/or doesn't work depending on which ones are installed on your system.

**Comment by cyjimmy** [comment]
Maybe I am doing something wrong here, I tried to use `0.2.0-alpha1`, but the error persists.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/51365909/192112026-b985d607-a398-4733-be1a-e726163c89c0.png">

When I removed `monoandroid11.0` from `TargetFrameworks`, then the error was gone and I could build the project.

**Comment by jonathanpeppers** [comment]
@cyjimmy yes only `monoandroid` target frameworks would try to import something directly by name:

https://github.com/xamarin/Xamarin.Legacy.Sdk/blob/39e597ecf439b86c104bf3d8e5d17f6527f2a200/src/Xamarin.Legacy.Sdk/Sdk/Xamarin.Legacy.Android.targets#L30

Since MAUI shipped in .NET 7 RC 1 recently, does `dotnet workload update` solve your problem? (the renamed .NET 6 packs are also on NuGet.org)

**Comment by jwong-pdftron** [comment]
I tried `dotnet workload update`, but the problem persists. I tried with another mac which also has the same issue.

**Comment by cyjimmy** [comment]
@jonathanpeppers I tried running `dotnet workload update`, and it updated the maui-ios and maui-android workloads, but the problem persists.

**Comment by jonathanpeppers** [comment]
Ok, it looks like if you get newer workloads you'll need to delete a `Directory.Build.props` in this repo, such as:

https://github.com/xamarin/Xamarin.Legacy.Sdk/pull/44

^^ If this PR is not green tomorrow, I'll keep investigating.

**Comment by cyjimmy** [comment]
I tried `0.2.0-alpha2` again and it is working now. Not sure why it was not working earlier. Thanks for your help!
