### ISSUE TITLE
MSB4064 : "TargetFramework" not available in task "GenerateBuildSessionId" loaded  from Xamarin.iOS.Tasks

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Legacy.Sdk#54]
I have this message in french so the translation may not be as accurate as it should.

Any Clue ?
I used that target list. It happens when adding Xamarin.iOS10.
```xml
<Project Sdk="Xamarin.Legacy.Sdk/0.2.0-alpha4">
  <PropertyGroup>
    <TargetFrameworks>Xamarin.iOS10;netstandard2.1;net7.0-android;net7.0-ios</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net7.0-ios'">15.0</SupportedOSPlatformVersion>
```

**Comment by jonathanpeppers** [comment]
Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

**Comment by softlion** [comment]
I switched from rider to VS and that fixed it.
