### ISSUE TITLE
Which monoandroid version can support android 21?

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Legacy.Sdk#56]
I try to bind a aar package that it support api 21.
But it seem like monoandroid can be only set to <targetframeworks> with the highest version monoandroid13.
So is it any workaround that set this property to support api21 to legacy project?

monoandroid12:

<img width="667" alt="Screenshot 2023-06-17 at 20 37 06" src="https://github.com/xamarin/Xamarin.Legacy.Sdk/assets/16309962/b749ae64-bccb-4a5d-9d7c-537c0ff27177">

monoandroid13:

<img width="679" alt="Screenshot 2023-06-17 at 20 42 50" src="https://github.com/xamarin/Xamarin.Legacy.Sdk/assets/16309962/cbad78dd-eb5e-4b6b-9a8e-a2b26f0db3d9">

monoandroid14:

<img width="429" alt="Screenshot 2023-06-17 at 20 45 07" src="https://github.com/xamarin/Xamarin.Legacy.Sdk/assets/16309962/8f3cb018-05a1-4b78-a434-5a8c15b982a4">

package support version:
<img width="530" alt="Screenshot 2023-06-17 at 21 03 50" src="https://github.com/xamarin/Xamarin.Legacy.Sdk/assets/16309962/904e6fa0-f11a-4211-8f0f-5d56dfa2369e">

**Comment by jonathanpeppers** [comment]
@jingliancui are you seeing the same behavior in a Xamarin.Android class library?

This issue might be with the bindings and nothing to do with Xamarin.Legacy.Sdk?

**Comment by jingliancui** [comment]
Hi @jonathanpeppers you are right. Issue is relates to the compiler. Monoandroid generated is different from net6android. 
This issue can be closed.Thanks.
